import os

f=open('input_file.txt','w')

n=input("Input the no. of nodes = ")
f.write(str(n))
f.write('\n')
deg=input("Input the degree = ")
f.write(str(deg))
f.write('\n')
f.close()
f=open('input_file2.txt','w')
n=input("Input the weight = ")
f.write(str(n))
f.close()
os.system('python graph_2.py')
os.system('python node_generation.py')
os.system('python hopping.py')
os.system('python xml_create.py')
os.system('java -cp frodo2/frodo2.jar frodo2.algorithms.AgentFactory GreedInd.xml frodo2/agents/MaxSum/MaxSumAgent.xml -timeout 3600000 >file.txt')
os.system('python dot_create.py')
os.system('g++ new_method.cpp')
os.system('a.exe > newoutput.txt')
os.system('g++ data_info.cpp')
os.system('a.exe')
os.system('python new_file.py')
os.system('python weight_cal.py')
os.system('output.txt')
